apiVersion: apps/v1
kind: Deployment
metadata:
  name: oddlaws-web
spec:
  selector:
    matchLabels:
      app: oddlaws-web
  template:
    metadata:
      labels:
        app: oddlaws-web
    spec:
      containers:
        - name: oddlaws-web
          image: web
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: oddlaws-web-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: oddlaws-db
                  key: uri
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
