apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
nameSuffix: -staging

resources:
  - ../../base/web
  - ../../base/bot
  - ingress.yaml

images:
  - name: web

labels:
  - includeSelectors: true
    pairs:
      environment: staging
